[build-system]
requires = [ "poetry>=1.0.0",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "ERPLibre"
version = "1.1.0"
description = "Easy way to configure Odoo community"
license = "AGPL-3.0-or-later"
authors = [ "Mathieu Benoit <mathben@technolibre.ca>",]

[tool.poetry.dependencies]
python = "^3.7.7"
Asterisk = "^0.0.8"
Babel = "2.3.4"
GitPython = "^3.1.12"
Jinja2 = "2.10.1"
Mako = "1.0.4"
MarkupSafe = "0.23"
Pillow = "6.1.0"
PyJWT = "1.7.1"
PyPDF2 = "1.26.0"
PyYAML = "4.2b4"
SOAPpy = "^0.12.22"
Sphinx = ">=2.4.0"
Voicent-Python = "^1.0"
Werkzeug = "0.11.15"
XlsxWriter = "0.9.3"
agithub = "^2.2.2"
altair = "^4.1.0"
argcomplete = "^1.12.2"
bokeh = "1.1.0"
boto = "^2.49.0"
boto3 = "1.9.102"
cachetools = ">=2.0.1"
cerberus = "^1.3.2"
chardet = "3.0.4"
code_writer = "^1.1.1"
colorama = "^0.4.4"
cryptography = "2.6.1"
cython = "^0.29.21"
ddt = "1.2.0"
decorator = "4.0.10"
docutils = "0.12"
ebaysdk = "2.1.5"
email_validator = "^1.1.2"
escpos = "^1.8"
extract-msg = "^0.28.0"
extract_msg = "^0.28.0"
factur-x = "^1.12"
feedparser = "5.2.1"
freezegun = "0.3.11"
geojson = "2.4.1"
gevent = "1.3.4"
gitpython = "^3.1.12"
giturlparse = "^0.10.0"
greenlet = "0.4.13"
html2text = "2016.9.19"
invoice2data = "^0.3.5"
iscompatible = "^0.1.1"
jira = "2.0.0"
keystoneauth1 = "3.14.0"
lasso = "^0.0.5"
libsass = "0.12.3"
lxml = "4.2.3"
matplotlib = ">=2.0.0"
mock = "2.0.0"
mpld3 = "0.3"
mysqlclient = "^2.0.3"
num2words = "0.5.6"
numpy = "^1.19.5"
oauthlib = "2.1.0"
"oca.decorators" = "^0.0.1"
ofxparse = "0.16"
openpyxl = "^3.0.5"
openupgradelib = "^2.0.0"
pandas = "1.2.0"
paramiko = "^2.7.2"
passlib = "1.6.5"
pdf2image = "^1.14.0"
pexpect = "^4.8.0"
phonenumbers = "^8.12.15"
plotly = "4.1.0"
premailer = "^3.7.0"
psutil = "4.3.1"
psycopg2 = "2.7.3.1"
py-Asterisk = "^0.5.18"
"py3o.formats" = "^0.3"
"py3o.template" = "^0.10.0"
pycountry = "^20.7.3"
pydot = "1.2.3"
pygount = "<1.2.0"
pyldap = "2.4.28"
pymssql = "^2.1.5"
pymysql = "^1.0.2"
pyotp = "^2.4.1"
pyparsing = "2.1.10"
pyproj = "^3.0.0"
pyserial = "3.1.1"
pysftp = "^0.2.9"
python-chess = "<0.24"
python-csv = "^0.0.13"
python-dateutil = "2.7.3"
python-git = "^2018.2.1"
python-json-logger = "0.1.5"
python-keystoneclient = "3.22.0"
python-slugify = ">=3.0.2"
python-stdnum = "^1.15"
python-swiftclient = "3.9.0"
python-u2flib-server = "^5.0.1"
python-u2flib_server = "^5.0.1"
pytz = "2017.3"
pyusb = "1.0.0"
pyzbar = "^0.1.8"
qrcode = "5.3"
raven = "^6.10.0"
redis = "2.10.5"
reportlab = "3.3.0"
requests = "2.20.0"
requests-mock = "^1.8.0"
requests-oauthlib = "1.1.0"
requests-toolbelt = "0.9.1"
retrying = "^1.3.3"
rotate_backups_s3 = "^0.3"
serial = "^0.0.97"
shapely = "1.6.4.post2"
simplejson = "^3.17.2"
slugify = "^0.0.1"
sphinx = ">=1.6.7"
sphinx-intl = "^2.0.1"
sphinx-patchqueue = ">=1.0"
sphinx_rtd_theme = "^0.5.1"
sqlalchemy = "^1.3.22"
statsd = "3.2.1"
suds-jurko = "0.6"
toml = "^0.10.2"
twython = "^3.8.2"
unidecode = "1.0.22"
vatnumber = "1.2"
vcrpy = ">=2.1.1"
vcrpy-unittest = "^0.1.7"
vobject = "0.9.3"
voicent-python = "^1.0"
webcolors = "1.10"
websocket-client = "^0.57.0"
wechatpy = "^1.8.14"
wheel = "^0.36.2"
xlrd = "1.0.0"
xlwt = "1.3"
xmltodict = "^0.12.0"
zeep = "^4.0.0"
zxcvbn = "^4.4.28"

[tool.poetry.dev-dependencies]
websocket_client = "^0.57.0"
